### ISSUE TITLE
B站UP主遮羞的预设合集（23.2.19）

### ISSUE THREAD

**Issue by zhexiuamoy** [lss233/awesome-chatgpt-qq-presets#1]
截止发文时，共有"高启强"、"MOSS" 、"小黑子"、"丁真"、"必应"、"答疑助手"、"张维为"、"怼我"_（无脑反驳）_ 、"夸我" _（无脑赞同）_、"辩手"、"律师" 、"小说家"、"诗人"、"疯子" 、"室内设计师"自制预设，现分享给大家，大家一起继续完善预设_（23.2.19）_。
**角色扮演类：**
  高启强预设：[gaoqiqiang.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776219/gaoqiqiang.txt)
  MOSS预设：[MOSS.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776224/MOSS.txt)
  小黑子预设：[ikun.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776221/ikun.txt)
  丁真预设：[dingzhen.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776217/dingzhen.txt)
  张维为预设：[zhangweiwei.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776228/zhangweiwei.txt)
  疯子预设：[crazy.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776213/crazy.txt)
  怼我预设：[debatestick.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776215/debatestick.txt)
  夸我预设：[welldone.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776227/welldone.txt)
**工具类：**
  辩手预设：[debater.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776214/debater.txt)
  律师预设：[lawyer.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776222/lawyer.txt)
  答疑助手预设：[Lss233.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776223/Lss233.txt)
  室内设计师预设：[shineisheji.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776226/shineisheji.txt)
  小说家预设：[novelist.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776229/novelist.txt)
  诗人预设：[poet.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776230/poet.txt)
  必应预设：[bing.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10776212/bing.txt)

**Comment by lss233** [comment]
很有意思的预设，感谢你的分享！
