### ISSUE TITLE
更新两个角色扮演类预设：韩立和胡锡进

### ISSUE THREAD

**Issue by zhexiuamoy** [lss233/awesome-chatgpt-qq-presets#3]
**韩立预设**：[hanli.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10781826/hanli.txt)
**胡锡进预设**：[huxijin.txt](https://github.com/lss233/awesome-chatgpt-qq-presets/files/10781828/huxijin.txt)

**Comment by lss233** [comment]
已收录
